project:
  type: website

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    right:
      - text: Home
        href: index.qmd

format:
  html:
    backgroundcolor: "#81a1c1"
    fontcolor: "#2e3440"
    linkcolor: "black"
    mainfont: "monospace"
    fontsize: 18px
    theme: [cosmo, styles.scss]