project:
  type: website

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  navbar:
    title: Theodore Hermann
    left:
      - text: Contact
        href: index.qmd
      - text: Projects
        href: projects/index.qmd
      - text: Dashboards
        menu:
          - text: Weather in Berlin
            href: https://mrguyperson.quarto.pub/berlin_weather/
      - text: CV
        menu:
          - text: Resume (Industry)
            href: cv/hermann_resume_industry.qmd          
          - text: Resume (Research)
            href: cv/hermann_resume_research.qmd
          - text: Full Curriculum Vitae
            href: cv/hermann_cv.qmd
  repo-url: https://github.com/mrguyperson/homepage
  repo-actions: [source]
  page-footer: 
    border: true

format:
  html:
    fontsize: 18px
    theme:
      dark: darkly
      light: flatly