project:
  type: website

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  navbar:
    title: Theodore Hermann
    left:
      - text: Contact
        href: index.qmd
      - text: CV
        menu:
          - text: Resume
            href: cv/cv_short.qmd
          - text: Curriculum Vitae
            href: cv/cv_full.qmd
  repo-url: https://github.com/mrguyperson/homepage
  repo-actions: [source]

format:
  html:
    fontsize: 18px
    theme:
      dark: darkly
      light: flatly