on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    - cron: '0 0 1 * *' # first of each month to handle any jobs with blank end date

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4 
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install libudunits2-dev libxtst6 libxt6 libmagick++-dev libglpk-dev cmake libnode-dev libgdal-dev gdal-bin libgeos-dev libproj-dev libsqlite3-dev libpng-dev libharfbuzz-dev libfribidi-dev
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.5.1
          use-public-rspm: true
      - name: Install R packages
        uses: r-lib/actions/setup-renv@v2
      - name: Set up tinytex
        uses: r-lib/actions/setup-tinytex@v2
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render and Publish 
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: quarto-pub
          QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUARTO_PUB_AUTH_TOKEN }}